export const GET_POKEMON_SUCCESS =  'GET_POKEMON_SUCCESS';
export const GET_POKEMON_FAILED =   'GET_POKEMON_FAILED';
export const GET_POKEMON_REQUEST =  'GET_POKEMON_REQUEST';

export const GET_POKEMONS_SUCCESS = 'GET_POKEMONS_SUCCESS';
export const GET_POKEMONS_FAILED =  'GET_POKEMONS_FAILED';
export const GET_POKEMONS_REQUEST = 'GET_POKEMONS_REQUEST';

export const USER_AUTHORIZATION_SUCCESS =   'USER_AUTHORIZATION_SUCCESS';
export const USER_AUTHORIZATION_FAILED =    'USER_AUTHORIZATION_FAILED';
export const USER_AUTHORIZATION_REQUEST =   'USER_AUTHORIZATION_REQUEST';

export const USER_STATUS_AUTHORIZATED =     'USER_STATUS_AUTHORIZATED';
export const USER_STATUS_NON_AUTHORIZATED = 'USER_STATUS_NON_AUTHORIZATED';

export const UNDEFINED = undefined;
