export const USER_ADDS_TO_FAVORITES_SUCCESS = 'USER_ADDS_TO_FAVORITES_SUCCESS';
export const USER_ADDS_TO_FAVORITES_FAILED =  'USER_ADDS_TO_FAVORITES_FAILED';
export const USER_ADDS_TO_FAVORITES_REQUEST = 'USER_ADDS_TO_FAVORITES_REQUEST';

export const USER_DELETES_FROM_FAVORITES_SUCCESS = 'USER_DELETES_FROM_FAVORITES_SUCCESS';
export const USER_DELETES_FROM_FAVORITES_FAILED =  'USER_DELETES_FROM_FAVORITES_FAILED';
export const USER_DELETES_FROM_FAVORITES_REQUEST = 'USER_DELETES_FROM_FAVORITES_REQUEST';

export const USER_LOGOUT = 'USER_LOGOUT';
