export const USER_AUTHORIZATION_SUCCESS =   'USER_AUTHORIZATION_SUCCESS';
export const USER_AUTHORIZATION_FAILED =    'USER_AUTHORIZATION_FAILED';
export const USER_AUTHORIZATION_REQUEST =   'USER_AUTHORIZATION_REQUEST';

export const USER_STATUS_AUTHORIZATED =     'USER_STATUS_AUTHORIZATED';
export const USER_STATUS_NON_AUTHORIZATED = 'USER_STATUS_NON_AUTHORIZATED';
